@echo off
echo Inizializzo il Virtual Environment...
virtualenv venv
echo Attivo il Virtual Environment...
call .\venv\Scripts\activate.bat
echo Installo tutti i pacchetti...
pip install -r requirements.txt
echo Avvio il Notebook Jupyter...
jupyter notebook