@echo off
echo Installo virtualenv...
pip install virtualenv
echo Inizializzo il Virtual Environment...
python -m virtualenv venv
echo Attivo il Virtual Environment...
call .\venv\Scripts\activate.bat
echo Installo tutti i pacchetti...
pip install -r requirements.txt
echo Avvio il Notebook Jupyter...
jupyter notebook